export enum GameEvent {
  startTrace = 'startTrace',
  hitWall = 'hitWall',
  startGame = 'startGame',
  playerStateChange = 'playerChange',
  gameStateChange = 'gameChange',
  gameOver = 'gameOver',
  newGame = 'newGame',
  openDoor = 'openDoor',
  doorCollision = 'doorCollision',
  goalCollision = 'goalCollision',
  doorSwitchCollision = 'doorSwitchcollision',
  levelComplete = 'levelComplete',
  selectCharacter = 'selectCharacter',
}
